# Copyright 2026 DANG NT (dangnt.vn@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Description: Initial schema — doctors, bookings (with the partial unique
#              index that makes double-booking impossible, ADR-0009),
#              knowledge_base, knowledge_chunks, ingestion_jobs, and
#              chat_session_links (ARCH-001 §6.1). Hand-written rather than
#              autogenerated — no live Postgres was available this pass.
#
#              Idempotency note (multi-server deploy, 2026-07-22): the 3
#              language-specific servers (vn/jp/en, see
#              0002_partition_knowledge_by_language.py and
#              0003_partition_business_tables_by_language.py) each track
#              migration history in their own alembic_version_{suffix} table
#              (alembic/env.py) on the one shared Postgres instance. That
#              means every server's *first* `alembic upgrade head` starts
#              from this revision's base state and replays this migration —
#              so every op.create_table()/op.create_index() call here is
#              guarded with an existence check: the first server to run it
#              actually creates the un-suffixed tables below, and every
#              subsequent server's replay is then a safe no-op instead of an
#              "already exists" error. ALL 6 tables created here
#              (doctors/bookings/chat_session_links, and
#              knowledge_base/knowledge_chunks/ingestion_jobs) are
#              immediately superseded by later migrations — 0002 drops the
#              3 knowledge/RAG tables and 0003 drops doctors/bookings/
#              chat_session_links (ADR-0024, 2026-07-22 — doctors partitioned
#              by language forced bookings/chat_session_links to follow via
#              the FK chain) in favour of the per-language-suffixed ones.
#              None of these 6 are "truly shared" any more; this migration
#              only exists as the from-base replay target every server's
#              independent alembic_version_{suffix} history starts at.
#
#              OPERATIONAL REQUIREMENT (code-reviewer finding, 2026-07-22
#              review 1/3): every _table_exists() guard below is a
#              check-then-act read, not an atomic compare-and-create — safe
#              only when the 3 servers run `alembic upgrade head` one at a
#              time (as intended: each is a one-off deploy step, not a
#              long-running concurrent process). Two servers migrating this
#              shared DB at the exact same moment could both pass the
#              existence check before either commits its create_table, then
#              both attempt to create the same table — this migration does
#              NOT guard against that race. Deploy runbooks must serialise
#              the 3 servers' first migration run.
###############################################################################
"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-02

"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def _table_exists(name: str) -> bool:
    """Whether ``name`` already exists on the DB this migration is running against.

    Used to guard every create/drop below so this migration is safe to replay
    (see module docstring) — a 2nd/3rd server's independent, from-base replay
    of this same revision must not error on tables an earlier server already
    created.
    """
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(name)


def upgrade() -> None:
    if not _table_exists("doctors"):
        op.create_table(
            "doctors",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("full_name", sa.String(255), nullable=False),
            sa.Column("title", sa.String(64)),
            sa.Column("specialty", sa.String(64), nullable=False),
            sa.Column("phone", sa.String(32)),
            sa.Column("work_days", sa.ARRAY(sa.String(16)), nullable=False, server_default="{}"),
            sa.Column("room", sa.String(32)),
            sa.Column("shift", sa.String(32)),
            sa.Column("fee", sa.Numeric(12, 2)),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.Column("bio", sa.String()),
            sa.Column("education", sa.String()),
            sa.Column("photo_url", sa.String(512)),
            sa.Column("extra", sa.JSON()),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        )

    if not _table_exists("bookings"):
        op.create_table(
            "bookings",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("patient_name", sa.String(255), nullable=False),
            sa.Column("phone", sa.String(32), nullable=False),
            sa.Column("doctor_id", sa.Integer(), sa.ForeignKey("doctors.id", ondelete="RESTRICT"), nullable=False),
            sa.Column("slot_time", sa.DateTime(timezone=True), nullable=False),
            sa.Column("status", sa.String(16), nullable=False, server_default="confirmed"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        )
        # Partial unique index (ADR-0009) — NOT a plain unique constraint. A
        # cancelled row must free its slot for a new booking, which a plain
        # UNIQUE on (doctor_id, slot_time) would forever block.
        op.create_index(
            "ix_bookings_doctor_slot_active",
            "bookings",
            ["doctor_id", "slot_time"],
            unique=True,
            postgresql_where=sa.text("status != 'cancelled'"),
        )

    if not _table_exists("knowledge_base"):
        op.create_table(
            "knowledge_base",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("category", sa.String(32), nullable=False),
            sa.Column("title", sa.String(255), nullable=False),
            sa.Column("content", sa.Text(), nullable=False),
            sa.Column("status", sa.String(16), nullable=False, server_default="draft"),
            sa.Column("last_indexed_at", sa.DateTime(timezone=True)),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        )

    if not _table_exists("knowledge_chunks"):
        op.create_table(
            "knowledge_chunks",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column(
                "knowledge_id", sa.Integer(), sa.ForeignKey("knowledge_base.id", ondelete="CASCADE"), nullable=False
            ),
            sa.Column("ordinal", sa.Integer(), nullable=False),
            sa.Column("text", sa.String(), nullable=False),
            sa.Column("vector_id", sa.String(64)),
            sa.Column("embed_status", sa.String(16), nullable=False, server_default="pending_embed"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        )

    if not _table_exists("ingestion_jobs"):
        op.create_table(
            "ingestion_jobs",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column(
                "knowledge_id", sa.Integer(), sa.ForeignKey("knowledge_base.id", ondelete="CASCADE"), nullable=False
            ),
            sa.Column("status", sa.String(16), nullable=False, server_default="pending_chunk"),
            sa.Column("error_msg", sa.String(500)),
            sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        )

    if not _table_exists("chat_session_links"):
        op.create_table(
            "chat_session_links",
            sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
            sa.Column("booking_id", sa.Integer(), sa.ForeignKey("bookings.id", ondelete="CASCADE"), nullable=False),
            sa.Column("session_id", sa.String(128), nullable=False),
            sa.Column("user_id", sa.String(128), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        )


def downgrade() -> None:
    # Guarded the same way as upgrade() (see module docstring) — a downgrade
    # replayed independently by more than one server's version tracking must
    # not error on tables an earlier downgrade already removed. Note this
    # drops the un-suffixed tables below (doctors/bookings/chat_session_links,
    # plus the 3 RAG tables) that only exist as this revision's from-base
    # replay target (see module docstring — 0002/0003 supersede them with
    # per-language-suffixed tables); running a downgrade to 0001's base while
    # another language server is still live against the same DB will break
    # that server — this was already true before the multi-server split and
    # downgrading a shared production DB was never a supported single-command
    # operation.
    if _table_exists("chat_session_links"):
        op.drop_table("chat_session_links")
    if _table_exists("ingestion_jobs"):
        op.drop_table("ingestion_jobs")
    if _table_exists("knowledge_chunks"):
        op.drop_table("knowledge_chunks")
    if _table_exists("knowledge_base"):
        op.drop_table("knowledge_base")
    if _table_exists("bookings"):
        op.drop_index("ix_bookings_doctor_slot_active", table_name="bookings")
        op.drop_table("bookings")
    if _table_exists("doctors"):
        op.drop_table("doctors")
